columns: 100
steps:
  - simple_align:
      cases: false
      top_level_patterns: false
      records: true

  - imports:
      align: group
      list_align: after_alias
      long_list_align: inline

  - language_pragmas:
      remove_redundant: true

language_extensions:
  - MultiParamTypeClasses
  - ExplicitForAll
